### ISSUE TITLE
Synthetic Data Questions

### ISSUE THREAD

**Issue by jknowles** [jhanelle-adams/sat-report-template#2]
Do we want the data to be wide by exam subject with multiple subject exams per student on a single row, or do we want the data to be unique by student-subject? Unique by student-subject (long data) plays better with tables and figures in R -- so that is my recommendation. 

The questions in the existing report assume some information outside of the AP data file -- specifically a denominator for rates of AP taking by school. Is that the intent of the report? It would be good to see what analysis we can using only the AP file itself first, then extend the report to include outside data.

**Comment by jhanelle-adams** [comment]
This is the raw data file. Should I have cleaned the data set first?

**Comment by jknowles** [comment]
No need to clean it - I'm surprised that's how it comes in, but it's good to know and be able to note that. I'll make the synthetic data align exactly!

I'll get this put together soon

**Comment by jhanelle-adams** [comment]
Ok! I did pare down some of the columns, because they were just repeated based on the number of AP subjects a student took, but these are all the variables.

Which means, I'll have to include the data wrangling code in the R markdown file right?

**Comment by jknowles** [comment]
Hi @jhanelle-adams - when you pared down the columns where did you document it? I don't see a commit - a change in the repository - from you that pares the columns down. Not a problem at the moment, but just a heads up that if you made changes they aren't reflected here.

**Comment by jknowles** [comment]
Done with the first set of data - check it out and submit corrections/improvements, etc.
